### ISSUE TITLE
Probing does not use high speed jerk value for stopping on contact with switch

### ISSUE THREAD

**Issue by RobMackie** [FabMo/FabMo-G2-Core#4]
**Description**
Probing is not using the "high speed jerk" setting when it hits the target in the axis being probed -- which I believe it should be.
Note that this is not a trivial issue of "just set high speed jerk before probing." Probing should use normal jerk for acceleration towards the switch and "high speed jerk" for deceleration upon contact, then make sure that the jerk value is set back to the original value before returning to normal.

So there is a question of whether or not the normal jerk logic should be in play. If it is, then the values need to be stashed for later restoration. And the logic on probe acceleration needs to be assymetrical - one value for accel and a different for decel.

**Solution criteria** 
There should be some easy method for fabmo to use where probes accelerate and a nominal specified jerk and decel at a specified very high jerk, and then return to normal jerk configuration. May require interface changes to provision the jerk rates, or it may be possible to use the existing values. Need to hear from Rob G how he figured it would work and from Ted how he's wanting to see it work.

**Reproduce:**
Probe on an axis (applies to all axes). Note rate of accel and rate of decel. (easiest to use a very low jerk for accel and a very high jerk for decel.  Not at all sure there is any way to configure different jerk levels in any naive way - needs investigation of how all of that works.

**Comment by Cosmic7373** [comment]
**This issue was discussed in ShopBot Slack on 9-9-21.**

**Rob G.** had this (and more) to say.
"Ok, so if we go with the probing feedhold uses high-jerk. That would require:

Make a function that sits next to _calculate_jerk  (at https://github.com/synthetos/g2/blob/edge-preview/g2core/plan_line.cpp#L463), maybe calling it mp_recalculate_jerk_for_feedhold(mpBuf_t *bf) 

That function would be called from [here ](https://github.com/synthetos/g2/blob/edge-preview/g2core/plan_exec.cpp#L1061)in _exec_aline_feedhold when and ONLY when cm->hold_state == FEEDHOLD_SYNC
It would set the bf->gm.motion_profile == PROFILE_FAST if bf->gm.motion_profile == PROFILE_FAST_STOP (which we would add as a new profile [here](https://github.com/synthetos/g2/blob/edge-preview/g2core/gcode.h#L93-L96))

Make probing (and maybe homing) set motion_profile == PROFILE_FAST_STOP  when it makes the primary move
We have to adjust feedhold to recompute a tail if we’re in the middle of one. That’s here: https://github.com/synthetos/g2/blob/edge-preview/g2core/plan_exec.cpp#L1062-L1069"
